### ISSUE TITLE
Fix wrapping in code blocks

### ISSUE THREAD

**Issue by detunized** [detunized/blog#2]
Change in `hermit/assets/scss/style.scss`:

```css
pre {
  white-space: pre;
  /*word-wrap: break-word;*/
}
```

The theme needs to be forked
