### ISSUE TITLE
Fix line breaks inside words of `inline code` tags (break-word)

### ISSUE THREAD

**Issue by detunized** [detunized/blog#3]
Change in `hermit/assets/scss/style.scss`:

```css
code {
  word-break: normal;
}
```
Check https://css-tricks.com/almanac/properties/o/overflow-wrap/
